defmodule Bitflyer.Repo.Migrations.AddTradingResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:balance_snapshots, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:currency, :text, null: false)
      add(:amount, :decimal, null: false)
      add(:available, :decimal, null: false)
      add(:captured_at, :utc_datetime_usec, null: false)
      add(:trade_mode, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:orders, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:internal_order_id, :text, null: false)
      add(:exchange_order_id, :text)
      add(:product_code, :text, null: false)
      add(:side, :text, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:order_type, :text, null: false, default: "limit")
      add(:price, :decimal)
      add(:size, :decimal, null: false)
      add(:filled_size, :decimal, null: false, default: "0")
      add(:trade_mode, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:orders, [:internal_order_id],
             name: "orders_unique_internal_order_id_index"
           )

    create table(:positions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:product_code, :text, null: false)
      add(:side, :text, null: false)
      add(:size, :decimal, null: false)
      add(:average_price, :decimal, null: false)
      add(:trade_mode, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:positions, [:product_code], name: "positions_unique_product_code_index")

    create table(:risk_states, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:name, :text, null: false, default: "default")
      add(:halted, :boolean, null: false, default: false)
      add(:reason, :text)
      add(:halted_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:risk_states, [:name], name: "risk_states_unique_name_index")
  end

  def down do
    drop_if_exists(unique_index(:risk_states, [:name], name: "risk_states_unique_name_index"))

    drop(table(:risk_states))

    drop_if_exists(
      unique_index(:positions, [:product_code], name: "positions_unique_product_code_index")
    )

    drop(table(:positions))

    drop_if_exists(
      unique_index(:orders, [:internal_order_id], name: "orders_unique_internal_order_id_index")
    )

    drop(table(:orders))

    drop(table(:balance_snapshots))
  end
end
