defmodule Bitflyer.Repo.Migrations.AddTradingLookupIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:balance_snapshots, [:trade_mode, :currency, :captured_at],
             name: "balance_snapshots_trade_mode_currency_captured_at_index"
           )

    create index(:orders, [:exchange_order_id], name: "orders_exchange_order_id_index")
  end

  def down do
    drop_if_exists(index(:orders, [:exchange_order_id], name: "orders_exchange_order_id_index"))

    drop_if_exists(
      index(:balance_snapshots, [:trade_mode, :currency, :captured_at],
        name: "balance_snapshots_trade_mode_currency_captured_at_index"
      )
    )
  end
end
