defmodule Bitflyer.Repo.Migrations.AlterPositionsUniqueProductCodeAndTradeMode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:positions, [:product_code], name: "positions_unique_product_code_index")
    )

    create unique_index(:positions, [:product_code, :trade_mode],
             name: "positions_unique_product_code_and_trade_mode_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:positions, [:product_code, :trade_mode],
        name: "positions_unique_product_code_and_trade_mode_index"
      )
    )

    create unique_index(:positions, [:product_code], name: "positions_unique_product_code_index")
  end
end
